name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker-compose build
    - name: Prepare DB
      run: docker-compose run --rm api rails db:prepare
    - name: Run tests
      run: docker-compose run --rm api rspec
